# Rebuild all reference datasets from raw source files.
# Run this script whenever a source file is updated.
# Output goes to data/ as .rda files for use in package functions and Rmds.

library(dplyr)
library(readxl)
library(usethis)
library(here)

# ── Species code generation helper ───────────────────────────────────────────
# Produces ACIMS-style codes: 4-letter genus + "." + 4-letter epithet (uppercase).
# Conflicts resolved by extending the epithet (up to 8 chars), then the genus
# (up to 6 chars), then a numeric suffix as a last resort.
# Identical binomials (same genus + epithet, e.g. duplicate rows or varieties
# with the same base species) receive the same code.
generate_spp_codes <- function(sci_names) {
  # Strip author citations and extract genus + primary specific epithet
  extract_binomial <- function(nm) {
    nm <- iconv(nm, to = "ASCII//TRANSLIT")          # remove diacritics
    nm <- gsub("\\s*\\([^)]*\\)", "", nm)             # drop parenthetical authors
    words <- strsplit(trimws(nm), "\\s+")[[1]]
    genus <- words[1]
    skip  <- c("x", "X", "ssp.", "ssp", "var.", "var", "f.", "fo.", "subsp.")
    rem   <- words[-1][!words[-1] %in% skip]
    epi   <- rem[grepl("^[a-z]", rem)]
    epi   <- if (length(epi)) epi[1] else "sp"
    paste(genus, epi)
  }

  binomials     <- vapply(sci_names, extract_binomial, character(1))
  unique_binom  <- unique(binomials)

  make_code <- function(binom, glen = 4, elen = 4) {
    p <- strsplit(binom, " ")[[1]]
    paste0(toupper(substr(p[1], 1, glen)), ".", toupper(substr(p[2], 1, elen)))
  }

  ucodes <- vapply(unique_binom, make_code, character(1))

  # Resolve conflicts iteratively: extend epithet then genus, suffix as fallback
  for (attempt in seq_len(20)) {
    dup_mask <- duplicated(ucodes) | duplicated(ucodes, fromLast = TRUE)
    if (!any(dup_mask)) break
    for (dc in unique(ucodes[dup_mask])) {
      idx      <- which(ucodes == dc)
      resolved <- FALSE
      for (elen in 5:8) {
        nc <- vapply(unique_binom[idx], make_code, character(1), glen = 4, elen = elen)
        if (length(unique(nc)) == length(idx) && !any(nc %in% ucodes[-idx])) {
          ucodes[idx] <- nc; resolved <- TRUE; break
        }
      }
      if (!resolved) {
        for (glen in 5:6) {
          for (elen in 4:8) {
            nc <- vapply(unique_binom[idx], make_code, character(1), glen = glen, elen = elen)
            if (length(unique(nc)) == length(idx) && !any(nc %in% ucodes[-idx])) {
              ucodes[idx] <- nc; resolved <- TRUE; break
            }
          }
          if (resolved) break
        }
      }
      if (!resolved) {
        for (i in seq_along(idx)[-1])
          ucodes[idx[i]] <- paste0(ucodes[idx[i]], "_", i)
      }
    }
  }

  names(ucodes) <- unique_binom
  unname(ucodes[binomials])
}

# ── Vegetation reference tables ───────────────────────────────────────────────

# AB Invasive Species Council species list
# Source: https://abinvasives.ca/
# TODO (Track 2): obtain invasive_species_ab.csv and uncomment
# invasive_species <- read.csv(here("data-raw", "invasive_species_ab.csv"))
# usethis::use_data(invasive_species, overwrite = TRUE)

# AB Weed Control Act — Noxious and Nuisance weeds
# Source: AB King's Printer / AEP
noxious_weeds <- read.csv(here("data-raw", "noxious_weeds_ab.csv"))
usethis::use_data(noxious_weeds, overwrite = TRUE)

# ACIMS Alberta vascular plant list (used as species validation lookup in QA/QC)
# Note: source file is the full ACIMS provincial plant list, not an ANPC wetland
# communities list. It serves the downstream purpose of validating species codes.
# Has 9 leading blank columns from original Excel export — skipped by column selection.
# Source: ACIMS / Alberta Biodiversity Monitoring Institute
anpc_raw <- read.csv(here("data-raw", "ANPC_Native_Plant_List.csv"),
                     stringsAsFactors = FALSE, encoding = "latin1")
# check.names = TRUE (default): "Scientific Name" → "Scientific.Name", etc.
# Duplicate "ORIGIN" column → "ORIGIN" and "ORIGIN.1"; we take the first.
anpc_wetland_species <- anpc_raw |>
  select(
    scientific_name = Scientific.Name,
    common_name     = Common.Name,
    origin          = ORIGIN,
    s_rank          = S_RANK
  ) |>
  filter(nzchar(trimws(scientific_name))) |>
  mutate(species_code = generate_spp_codes(scientific_name))
usethis::use_data(anpc_wetland_species, overwrite = TRUE)

# Alberta Wetland Classification System — full provincial plant list with class
# and indicator assignments derived from AWCS 2015 (ESRD Water Policy Branch).
# 622 species; 107 flagged as AWCS text indicators with fen type, bog form,
# marsh zone/salinity/hydroperiod, and swamp form detail columns.
# Source: ESRD 2015 Appendix C + classification text; ITIS 2014 taxonomy
# spp_code: ACIMS-style codes generated by generate_spp_codes(); stable as long
# as the source CSV row order and scientific names are unchanged.
awcs_wetland_species <- read.csv(here("data-raw", "awcs_wetland_species.csv"),
                                  stringsAsFactors = FALSE, encoding = "latin1") |>
  mutate(spp_code = generate_spp_codes(scientific_name)) |>
  relocate(spp_code, .before = scientific_name)
usethis::use_data(awcs_wetland_species, overwrite = TRUE)

# USDA PLANTS / NatureServe wetland indicator status (UPL–OBL)
# Source: Alberta Wetland Plant List 2021 (adapted from US Army Corps of Engineers
# regional lists for WMVC, GP, NCNE, AK regions).
# Row 1 is a merged title row; skip=1 makes row 2 the header.
wi_raw <- read.csv(here("data-raw", "ABWetlandPlantList_2021.csv"),
                   skip = 1, check.names = FALSE, stringsAsFactors = FALSE,
                   encoding = "latin1")
wetland_indicator_status <- wi_raw |>
  select(
    scientific_name = `Scientific Name (ACIMS)`,
    common_name     = `Common Name (ACIMS)`,
    wmvc = WMVC,
    gp   = GP,
    ncne = NCNE,
    ak   = AK
  ) |>
  filter(nzchar(trimws(scientific_name))) |>
  mutate(species_code = generate_spp_codes(scientific_name))
usethis::use_data(wetland_indicator_status, overwrite = TRUE)

# AB Rangeland Plants
# Source: AEP Rangeland Plants of Alberta (2023 edition)
rangeland_plants <- read.csv(here("data-raw", "RangePlants_2023.csv"),
                              stringsAsFactors = FALSE) |>
  rename(
    common_name      = Common.name,
    scientific_name  = Scientific.name,
    life_span        = Life.span,
    origin           = Origin,
    grazing_response = Grazing.response,
    forage_value     = Forage.value,
    stratum          = Stratum
  )
usethis::use_data(rangeland_plants, overwrite = TRUE)

# Plant salinity tolerance
# Source: literature compilation
# TODO (Track 2): obtain salinity_tolerance.csv and uncomment
# salinity_tolerance <- read.csv(here("data-raw", "salinity_tolerance.csv"))
# usethis::use_data(salinity_tolerance, overwrite = TRUE)

# Northern Forestry Centre ecosites
# Source: NRCan/CFS ecosite classification
# NOTE: Ecosite_to_WetClass.csv is a wetland class ↔ NFC ecosite crosswalk
# (Beckingham & Archibald 1996), NOT the NFC ecosite classification table itself.
# ecosites_nfc is not yet actively used in pipeline Rmds (TODO placeholder).
# TODO (Track 2): obtain or author proper ecosites_nfc.csv and uncomment
# ecosites_nfc <- read.csv(here("data-raw", "ecosites_nfc.csv"))
# usethis::use_data(ecosites_nfc, overwrite = TRUE)

# NRC geography regions and USACE geographic region linkage
# TODO (Track 2): obtain nrc_geography_usace.csv and uncomment
# nrc_geography <- read.csv(here("data-raw", "nrc_geography_usace.csv"))
# usethis::use_data(nrc_geography, overwrite = TRUE)

# WAIR wetland classification decision rules (structured table)
# TODO (Track 2): author wair_classification_rules.csv from WAIR document and uncomment
# wair_rules <- read.csv(here("data-raw", "wair_classification_rules.csv"))
# usethis::use_data(wair_rules, overwrite = TRUE)

# ── Soils reference tables ────────────────────────────────────────────────────

# Canadian System of Soil Classification — great groups / orders
cssc_great_groups <- read.csv(here("data-raw", "cssc_great_groups.csv"))
usethis::use_data(cssc_great_groups, overwrite = TRUE)

# Von Post peat humification scale (H1–H10)
# Source: Von Post (1922); standard as used in Canadian peat assessment.
# Raw CSV has merged-cell headers from Excel export; data values are at
# column positions 1, 6, 10, 15, 20 (degree, liquid, extruded, plant matter, description).
von_post_raw <- read.csv(here("data-raw", "Van_Post_List.csv"),
                          check.names = FALSE, stringsAsFactors = FALSE)
von_post <- data.frame(
  von_post_code = paste0("H", trimws(von_post_raw[[1]])),
  liquid        = trimws(von_post_raw[[6]]),
  extruded      = trimws(von_post_raw[[10]]),
  plant_matter  = trimws(von_post_raw[[15]]),
  description   = trimws(von_post_raw[[20]]),
  stringsAsFactors = FALSE
)
usethis::use_data(von_post, overwrite = TRUE)

# Munsell soil colour chart
# TODO (Track 2): obtain munsell.csv and uncomment
# munsell <- read.csv(here("data-raw", "munsell.csv"))
# usethis::use_data(munsell, overwrite = TRUE)

# AGRASID soil map units (Alberta Geomatic Reference for Agriculture and Soils)
# Source: AB Agriculture
# TODO (Track 2): obtain agrasid.csv and uncomment
# agrasid <- read.csv(here("data-raw", "agrasid.csv"))
# usethis::use_data(agrasid, overwrite = TRUE)
